// ─── DEMO GRAPH (fallback when backend is offline) ────────────────
function loadDemoGraph() {
    const demoSources = [
        {title:"Wikipedia — Elon Musk", url:"https://en.wikipedia.org/wiki/Elon_Musk", body:"Comprehensive biography"},
        {title:"Reuters",               url:"https://reuters.com",                       body:"Business reporting"},
        {title:"The Guardian",          url:"https://theguardian.com",                   body:"News"},
        {title:"Bloomberg",             url:"https://bloomberg.com",                     body:"Finance"},
    ];

    const nodes = [
        {id:"Elon Musk",type:"Central",label:"Elon Musk",summary:"## Executive Dossier\n**Born:** June 28, 1971, Pretoria, South Africa\n**Net Worth:** ~$200B+\n\nElon Musk is the world's most consequential tech entrepreneur — simultaneously CEO of Tesla, SpaceX, X (Twitter), xAI, Neuralink, and The Boring Company. His ambitions span decarbonizing transport, colonizing Mars, and merging human cognition with AI.",details:"Tech Billionaire"},
        {id:"cat_origins",type:"Category",label:"🌍 ORIGINS",summary:"## Origins\nMusk's formative years in apartheid-era South Africa instilled radical self-reliance. He emigrated at 17, first to Canada, then USA.",details:"Category"},
        {id:"cat_career",type:"Category",label:"🚀 CAREER",summary:"## Career\nSeven major companies built with extreme risk tolerance across finance, transport, energy, space, AI, and media.",details:"Category"},
        {id:"cat_network",type:"Category",label:"🕸 NETWORK",summary:"## Network\nMusk's circle spans family, partners, ideological allies and rivals — amplified by 200M+ X followers.",details:"Category"},
        {id:"cat_controversy",type:"Category",label:"⚡ CONTROVERSIES",summary:"## Controversies\nSEC enforcement, workplace misconduct, advertiser boycotts, and political interference allegations.",details:"Category"},
        {id:"cat_ideology",type:"Category",label:"💡 IDEOLOGY",summary:"## Ideology\nFree speech absolutism, techno-accelerationism, existential risk reduction, and libertarian minimalism.",details:"Category"},
        {id:"Pretoria",type:"Entity",label:"Pretoria, SA",summary:"Birthplace. Sold first video game 'Blastar' at age 12 for $500.",details:"Birthplace"},
        {id:"Errol Musk",type:"Entity",label:"Errol Musk",summary:"Father — electromechanical engineer. Elon describes relationship as 'deeply difficult'.",details:"Father"},
        {id:"Maye Musk",type:"Entity",label:"Maye Musk",summary:"Mother — Canadian-South African model and dietitian. Close relationship with Elon.",details:"Mother"},
        {id:"Kimbal Musk",type:"Entity",label:"Kimbal Musk",summary:"Younger brother. Co-founded Zip2. Tesla board member and philanthropist.",details:"Sibling"},
        {id:"UPenn",type:"Entity",label:"UPenn / Wharton",summary:"Degrees in Economics and Physics. Dropped Stanford PhD after 2 days to start Zip2.",details:"Education"},
        {id:"Zip2",type:"Entity",label:"Zip2",summary:"First company — city guide software. Sold to Compaq for $307M in 1999.",details:"Company 1995–1999"},
        {id:"PayPal",type:"Entity",label:"X.com / PayPal",summary:"Founded X.com, merged to form PayPal. Acquired by eBay for $1.5B in 2002.",details:"Company 1999–2002"},
        {id:"SpaceX",type:"Entity",label:"SpaceX",summary:"Founded 2002, $100M personal investment. Reusable Falcon 9, Starlink, Starship. Multiple NASA contracts.",details:"Company 2002–present"},
        {id:"Tesla",type:"Entity",label:"Tesla Inc.",summary:"Chairman 2004, CEO 2008. Revolutionized EV market. Market cap briefly exceeded $1 trillion.",details:"Company 2004–present"},
        {id:"Neuralink",type:"Entity",label:"Neuralink",summary:"Brain-computer interface. First human implant January 2024. Goal: merge humans with AI.",details:"Company 2016–present"},
        {id:"Boring Co",type:"Entity",label:"The Boring Co.",summary:"Tunneling infrastructure. Built Las Vegas Convention Center Loop.",details:"Company 2016–present"},
        {id:"X Twitter",type:"Entity",label:"X (fka Twitter)",summary:"Acquired October 2022 for $44B. Rebranded, mass layoffs (75%), advertiser exodus.",details:"Company 2022–present"},
        {id:"xAI",type:"Entity",label:"xAI / Grok",summary:"AI company founded 2023. Grok LLM. $6B raised at $18B valuation. Rival to OpenAI, Anthropic, Google.",details:"Company 2023–present"},
        {id:"SolarCity",type:"Entity",label:"SolarCity",summary:"Controversial $2.6B Tesla acquisition in 2016. Shareholder lawsuits for self-dealing followed.",details:"Acquired 2016"},
        {id:"Grimes",type:"Entity",label:"Grimes",summary:"Canadian musician, partner ~2018–2022. Mother of X Æ A-12, Exa, and Tau.",details:"Former Partner"},
        {id:"Justine Musk",type:"Entity",label:"Justine Musk",summary:"First wife — Canadian author. Married 2000–2008. Six children including twins and triplets.",details:"Ex-Wife #1"},
        {id:"Peter Thiel",type:"Entity",label:"Peter Thiel",summary:"PayPal co-founder, Palantir billionaire. Libertarian ideological ally. PayPal Mafia member.",details:"Ally"},
        {id:"Sam Altman",type:"Entity",label:"Sam Altman",summary:"OpenAI CEO. Musk departed from OpenAI board 2018, sued Altman in 2024 for abandoning nonprofit mission.",details:"Rival"},
        {id:"Jeff Bezos",type:"Entity",label:"Jeff Bezos",summary:"Amazon founder, Blue Origin founder. Long-running space rivalry — SpaceX vs Blue Origin, NASA contracts.",details:"Rival"},
        {id:"Trump",type:"Entity",label:"Donald Trump",summary:"Musk endorsed Trump 2024, appointed to lead DOGE advisory role after election win.",details:"Political Ally"},
        {id:"SEC 2018",type:"Entity",label:"SEC Clash 2018",summary:"'$420 funding secured' tweet. Settled with $20M fine, resigned as Tesla Chairman for 3 years.",details:"Legal"},
        {id:"Twitter Chaos",type:"Entity",label:"Twitter/X Turmoil",summary:"75% staff layoffs, advertiser boycott, reinstated suspended accounts, chaotic content policy reversals.",details:"Controversy"},
        {id:"DOGE Controversy",type:"Entity",label:"DOGE Controversy",summary:"Unelected power concerns, conflict-of-interest allegations, massive federal job and spending cuts.",details:"Political"},
        {id:"OpenAI Lawsuit",type:"Entity",label:"OpenAI Lawsuit",summary:"Musk sued OpenAI in 2024 alleging abandonment of nonprofit mission. Case ongoing as of 2025.",details:"Legal"},
        {id:"Free Speech",type:"Entity",label:"Free Speech Absolutism",summary:"Core tenet driving Twitter acquisition. Reversed content moderation at scale across the platform.",details:"Belief"},
        {id:"Mars Colony",type:"Entity",label:"Mars Colonization",summary:"Primary civilizational mission. Starship designed to carry 100+ people to Mars per trip.",details:"Vision"},
        {id:"AI Risk",type:"Entity",label:"AI Existential Risk",summary:"Co-founded OpenAI for safety research, departed 2018, then founded xAI as alternative approach.",details:"Concern"},
        {id:"DOGE Initiative",type:"Entity",label:"DOGE Initiative",summary:"Department of Government Efficiency — federal spending cuts advisory role. Cut thousands of jobs, 2025.",details:"Political"},
    ];

    nodes.forEach(n => { nodeSources[n.id] = demoSources; });

    const edges = [
        {source:"Elon Musk",target:"cat_origins",relation:"EMERGED_FROM",desc:"Formative background shaped ambition"},
        {source:"Elon Musk",target:"cat_career",relation:"BUILT",desc:"30+ years serial entrepreneurship"},
        {source:"Elon Musk",target:"cat_network",relation:"CONNECTED_TO",desc:"Personal and professional relationships"},
        {source:"Elon Musk",target:"cat_controversy",relation:"EMBROILED_IN",desc:"Multiple high-profile disputes"},
        {source:"Elon Musk",target:"cat_ideology",relation:"DRIVEN_BY",desc:"Core philosophical worldview"},
        {source:"cat_origins",target:"Pretoria",relation:"BORN_IN",desc:"Birthplace 1971"},
        {source:"cat_origins",target:"Errol Musk",relation:"SON_OF",desc:"Complex paternal relationship"},
        {source:"cat_origins",target:"Maye Musk",relation:"SON_OF",desc:"Close maternal bond"},
        {source:"cat_origins",target:"Kimbal Musk",relation:"SIBLING",desc:"Lifelong close collaboration"},
        {source:"cat_origins",target:"UPenn",relation:"GRADUATED",desc:"Economics and Physics degrees"},
        {source:"cat_career",target:"Zip2",relation:"FOUNDED",desc:"Sold 1999 for $307M"},
        {source:"cat_career",target:"PayPal",relation:"CO-FOUNDED",desc:"Acquired by eBay 2002 for $1.5B"},
        {source:"cat_career",target:"SpaceX",relation:"FOUNDED",desc:"Founded 2002, personally invested $100M"},
        {source:"cat_career",target:"Tesla",relation:"LED_AS_CEO",desc:"CEO since 2008"},
        {source:"cat_career",target:"Neuralink",relation:"CO-FOUNDED",desc:"Brain-computer interface company 2016"},
        {source:"cat_career",target:"Boring Co",relation:"FOUNDED",desc:"Tunneling infrastructure 2016"},
        {source:"cat_career",target:"X Twitter",relation:"ACQUIRED",desc:"$44B acquisition October 2022"},
        {source:"cat_career",target:"xAI",relation:"FOUNDED",desc:"AI company founded 2023"},
        {source:"cat_career",target:"SolarCity",relation:"OVERSAW",desc:"Controversial $2.6B Tesla acquisition"},
        {source:"cat_network",target:"Grimes",relation:"PARTNER",desc:"Romantic partner 2018–2022, 3 children"},
        {source:"cat_network",target:"Justine Musk",relation:"EX-WIFE",desc:"Married 2000–2008, 6 children"},
        {source:"cat_network",target:"Peter Thiel",relation:"ALLY",desc:"PayPal Mafia co-founder, shared ideology"},
        {source:"cat_network",target:"Sam Altman",relation:"RIVAL",desc:"OpenAI co-founder split 2018"},
        {source:"cat_network",target:"Jeff Bezos",relation:"RIVAL",desc:"Space race SpaceX vs Blue Origin"},
        {source:"cat_network",target:"Trump",relation:"POLITICAL_ALLY",desc:"Endorsed 2024, DOGE role appointed"},
        {source:"cat_controversy",target:"SEC 2018",relation:"CHARGED",desc:"$20M settlement, Chairman resignation"},
        {source:"cat_controversy",target:"Twitter Chaos",relation:"CAUSED",desc:"Post-acquisition management turmoil"},
        {source:"cat_controversy",target:"DOGE Controversy",relation:"INVOLVED_IN",desc:"Unelected power controversy"},
        {source:"cat_controversy",target:"OpenAI Lawsuit",relation:"FILED",desc:"Filed February 2024"},
        {source:"cat_ideology",target:"Free Speech",relation:"CHAMPIONS",desc:"Core driver of Twitter acquisition"},
        {source:"cat_ideology",target:"Mars Colony",relation:"OBSESSES_OVER",desc:"Primary civilizational mission"},
        {source:"cat_ideology",target:"AI Risk",relation:"WARNS_ABOUT",desc:"Founded OpenAI then departed for xAI"},
        {source:"cat_ideology",target:"DOGE Initiative",relation:"SPEARHEADS",desc:"Federal efficiency advisory 2025"},
        {source:"SpaceX",target:"Mars Colony",relation:"VEHICLE_FOR",desc:"Starship is the hardware for Mars"},
        {source:"xAI",target:"AI Risk",relation:"RESPONSE_TO",desc:"Built as truth-seeking AI alternative"},
        {source:"Sam Altman",target:"OpenAI Lawsuit",relation:"TARGET_OF",desc:"Musk sued Altman and OpenAI 2024"},
        {source:"Peter Thiel",target:"PayPal",relation:"CO-FOUNDED",desc:"PayPal Mafia origin story"},
        {source:"Tesla",target:"DOGE Controversy",relation:"ENTANGLED_WITH",desc:"Federal contract conflicts of interest"},
        {source:"Trump",target:"DOGE Initiative",relation:"APPOINTED_MUSK_TO",desc:"Post-2024 election advisory role"},
        {source:"Kimbal Musk",target:"Tesla",relation:"BOARD_MEMBER",desc:"Director on Tesla board of directors"},
        {source:"X Twitter",target:"Free Speech",relation:"EMBODIES",desc:"Platform operationalizing Musk's ideology"},
    ];

    renderGraph(nodes, edges);
}